export default {
  index: 'Introduction',
  'getting-started': 'Getting Started',
  'local-dev': 'Local Dev Emulator',
  architecture: 'Architecture',
  'contract-api': 'Contract API',
  'sdk-reference': 'SDK Reference',
  'sdk-errors': 'SDK Error Reference',
  troubleshooting: 'Troubleshooting',
  guides: 'Guides',
  cookbook: 'Cookbook',
  'agent-integration': 'Agent Integration',
  security: 'Security',
  'threat-model': 'Threat Model',
}
